//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juz\&apos; %1$d.
        /// </summary>
        public static string juz2_description {
            get {
                return ResourceManager.GetString("juz2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madani.
        /// </summary>
        public static string madani {
            get {
                return ResourceManager.GetString("madani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мakki.
        /// </summary>
        public static string makki {
            get {
                return ResourceManager.GetString("makki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page %1$d, Juz\&apos; %2$d.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah.
        /// </summary>
        public static string quran_ayah {
            get {
                return ResourceManager.GetString("quran_ayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juz\&apos;.
        /// </summary>
        public static string quran_juz2 {
            get {
                return ResourceManager.GetString("quran_juz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura.
        /// </summary>
        public static string quran_sura {
            get {
                return ResourceManager.GetString("quran_sura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surat.
        /// </summary>
        public static string quran_sura_title {
            get {
                return ResourceManager.GetString("quran_sura_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura %1$s, Ayah %2$d.
        /// </summary>
        public static string sura_ayah_notification_str {
            get {
                return ResourceManager.GetString("sura_ayah_notification_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;string-array name=&quot;sura_names&quot;&gt;
        ///        &lt;item&gt;Al-Fatiha&lt;/item&gt;
        ///        &lt;item&gt;Al-Baqara&lt;/item&gt;
        ///        &lt;item&gt;Aal-E-Imran&lt;/item&gt;
        ///        &lt;item&gt;An-Nisa&lt;/item&gt;
        ///        &lt;item&gt;Al-Maeda&lt;/item&gt;
        ///        &lt;item&gt;Al-Anaam&lt;/item&gt;
        ///        &lt;item&gt;Al-Araf&lt;/item&gt;
        ///        &lt;item&gt;Al-Anfal&lt;/item&gt;
        ///        &lt;item&gt;At-Tawba&lt;/item&gt;
        ///        &lt;item&gt;Yunus&lt;/item&gt;
        ///        &lt;item&gt;Hud&lt;/item&gt;
        ///        &lt;item&gt;Yusuf&lt;/item&gt;
        ///        &lt;item&gt;Ar-Rad&lt;/item&gt;
        ///        &lt;item&gt;Ibrahim&lt;/item&gt;
        ///        &lt;item&gt;Al-Hijr&lt;/item&gt;
        ///        &lt;item&gt;An-Nahl&lt;/it [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sura_names {
            get {
                return ResourceManager.GetString("sura_names", resourceCulture);
            }
        }
    }
}
