//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranPhone.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranPhone.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Phone is a free, open source Quran
        ///application for Windows Phone based on Quran 
        ///Android project.  The images used are from the
        ///&amp;lt;a href=&quot;http://quran.com&quot;&gt;quran.com&amp;lt;/a&gt;
        ///project, the audio comes from
        ///&amp;lt;a href=&quot;http://everyayah.com&quot;&gt;everyayah.com&amp;lt;/a&gt;,
        ///the data used in the translations and Arabic comes from
        ///&amp;lt;a href=&quot;http://tanzil.net&quot;&gt;tanzil.net&amp;lt;/a&gt; and
        ///&amp;lt;a href=&quot;http://quran.ksu.edu.sa&quot;&gt;quran.ksu.edu.sa&amp;lt;/a&gt;
        ///&amp;lt;br/&gt;&amp;lt;br/&gt;&amp;lt;b&gt;Quran for Windows Phone Contributors:&amp;lt;/b&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string about_us_text {
            get {
                return ResourceManager.GetString("about_us_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QURAN.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available translations.
        /// </summary>
        public static string available_translations {
            get {
                return ResourceManager.GetString("available_translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark ayah.
        /// </summary>
        public static string bookmark_ayah {
            get {
                return ResourceManager.GetString("bookmark_ayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string bookmarks {
            get {
                return ResourceManager.GetString("bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah Bookmarks.
        /// </summary>
        public static string bookmarks_ayah {
            get {
                return ResourceManager.GetString("bookmarks_ayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        public static string bookmarks_current_page {
            get {
                return ResourceManager.GetString("bookmarks_current_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Bookmarks.
        /// </summary>
        public static string bookmarks_page {
            get {
                return ResourceManager.GetString("bookmarks_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change language.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bookmark.
        /// </summary>
        public static string delete_bookmark {
            get {
                return ResourceManager.GetString("delete_bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prevent phone from turning screen off.
        /// </summary>
        public static string disable_sleep {
            get {
                return ResourceManager.GetString("disable_sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to cancel download?.
        /// </summary>
        public static string download_cancel_confirmation {
            get {
                return ResourceManager.GetString("download_cancel_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded translations.
        /// </summary>
        public static string downloaded_translations {
            get {
                return ResourceManager.GetString("downloaded_translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For optimal performance, some files must be downloaded.  If you choose not to do this now, each page will take significantly longer to load. Would you like to download the required files now (WiFi connection recommended)?.
        /// </summary>
        public static string downloadPrompt {
            get {
                return ResourceManager.GetString("downloadPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Required Files?.
        /// </summary>
        public static string downloadPrompt_title {
            get {
                return ResourceManager.GetString("downloadPrompt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dua.
        /// </summary>
        public static string dua {
            get {
                return ResourceManager.GetString("dua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Downloaded File....
        /// </summary>
        public static string extracting_message {
            get {
                return ResourceManager.GetString("extracting_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate bookmarks for Quranic dua.
        /// </summary>
        public static string generate_bookmarks_for_dua {
            get {
                return ResourceManager.GetString("generate_bookmarks_for_dua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juz&apos; {0}.
        /// </summary>
        public static string juz2_description {
            get {
                return ResourceManager.GetString("juz2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show page info in landscape.
        /// </summary>
        public static string keep_info_overlay {
            get {
                return ResourceManager.GetString("keep_info_overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Quran data....
        /// </summary>
        public static string loading_message {
            get {
                return ResourceManager.GetString("loading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madani.
        /// </summary>
        public static string madani {
            get {
                return ResourceManager.GetString("madani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мakki.
        /// </summary>
        public static string makki {
            get {
                return ResourceManager.GetString("makki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to night mode.
        /// </summary>
        public static string night_mode {
            get {
                return ResourceManager.GetString("night_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we were unable to load the data due to absence of network connection. Please try again later..
        /// </summary>
        public static string no_network_to_load {
            get {
                return ResourceManager.GetString("no_network_to_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No translation to search. Please go to settings page to select active translation..
        /// </summary>
        public static string no_translation_to_search {
            get {
                return ResourceManager.GetString("no_translation_to_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page %1$d, Juz&apos; %2$d.
        /// </summary>
        public static string page_description {
            get {
                return ResourceManager.GetString("page_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please relaunch an app for the change to take effect.
        /// </summary>
        public static string please_restart {
            get {
                return ResourceManager.GetString("please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show ayah in Arabic above the translation.
        /// </summary>
        public static string prefs_ayah_before_translation_summary {
            get {
                return ResourceManager.GetString("prefs_ayah_before_translation_summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;resources&gt;
        ///        &lt;string-array name=&quot;quarter_prefix_array&quot;&gt;
        ///        &lt;item&gt;بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ&lt;/item&gt;
        ///        &lt;item&gt;إِنَّ اللَّهَ لَا يَسْتَحْيِي أَن&lt;/item&gt;
        ///        &lt;item&gt;أَتَأْمُرُونَ النَّاسَ بِالْبِرِّ&lt;/item&gt;
        ///        &lt;item&gt;وَإِذِ اسْتَسْقَىٰ مُوسَىٰ لِقَوْمِهِ&lt;/item&gt;
        ///        &lt;item&gt;أَفَتَطْمَعُونَ أَن يُؤْمِنُوا لَكُمْ&lt;/item&gt;
        ///        &lt;item&gt;وَلَقَدْ جَاءَكُم مُّوسَىٰ&lt;/item&gt;
        ///        &lt;item&gt;مَا نَنسَخْ مِنْ آيَةٍ أَوْ نُنسِهَا&lt;/item&gt;
        ///        &lt;item&gt;وَ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string quarters {
            get {
                return ResourceManager.GetString("quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah.
        /// </summary>
        public static string quran_ayah {
            get {
                return ResourceManager.GetString("quran_ayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmarks.
        /// </summary>
        public static string quran_bookmarks_lower {
            get {
                return ResourceManager.GetString("quran_bookmarks_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juz&apos;.
        /// </summary>
        public static string quran_juz2 {
            get {
                return ResourceManager.GetString("quran_juz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to juz&apos;.
        /// </summary>
        public static string quran_juz2_lower {
            get {
                return ResourceManager.GetString("quran_juz2_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string quran_page {
            get {
                return ResourceManager.GetString("quran_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rub&apos;.
        /// </summary>
        public static string quran_rub3 {
            get {
                return ResourceManager.GetString("quran_rub3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura.
        /// </summary>
        public static string quran_sura {
            get {
                return ResourceManager.GetString("quran_sura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sura.
        /// </summary>
        public static string quran_sura_lower {
            get {
                return ResourceManager.GetString("quran_sura_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surat.
        /// </summary>
        public static string quran_sura_title {
            get {
                return ResourceManager.GetString("quran_sura_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags.
        /// </summary>
        public static string quran_tags_lower {
            get {
                return ResourceManager.GetString("quran_tags_lower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search results.
        /// </summary>
        public static string search_results {
            get {
                return ResourceManager.GetString("search_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura %1$s, Ayah %2$d.
        /// </summary>
        public static string sura_ayah_notification_str {
            get {
                return ResourceManager.GetString("sura_ayah_notification_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;string-array name=&quot;sura_names&quot;&gt;
        ///        &lt;item&gt;Al-Fatiha&lt;/item&gt;
        ///        &lt;item&gt;Al-Baqara&lt;/item&gt;
        ///        &lt;item&gt;Aal-E-Imran&lt;/item&gt;
        ///        &lt;item&gt;An-Nisa&lt;/item&gt;
        ///        &lt;item&gt;Al-Maeda&lt;/item&gt;
        ///        &lt;item&gt;Al-Anaam&lt;/item&gt;
        ///        &lt;item&gt;Al-Araf&lt;/item&gt;
        ///        &lt;item&gt;Al-Anfal&lt;/item&gt;
        ///        &lt;item&gt;At-Tawba&lt;/item&gt;
        ///        &lt;item&gt;Yunus&lt;/item&gt;
        ///        &lt;item&gt;Hud&lt;/item&gt;
        ///        &lt;item&gt;Yusuf&lt;/item&gt;
        ///        &lt;item&gt;Ar-Rad&lt;/item&gt;
        ///        &lt;item&gt;Ibrahim&lt;/item&gt;
        ///        &lt;item&gt;Al-Hijr&lt;/item&gt;
        ///        &lt;item&gt;An-Nahl&lt;/it [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sura_names {
            get {
                return ResourceManager.GetString("sura_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation text size.
        /// </summary>
        public static string text_size {
            get {
                return ResourceManager.GetString("text_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translations.
        /// </summary>
        public static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verse.
        /// </summary>
        public static string verse {
            get {
                return ResourceManager.GetString("verse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verses.
        /// </summary>
        public static string verses {
            get {
                return ResourceManager.GetString("verses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for power....
        /// </summary>
        public static string waiting_for_power {
            get {
                return ResourceManager.GetString("waiting_for_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for WIFI....
        /// </summary>
        public static string waiting_for_wifi {
            get {
                return ResourceManager.GetString("waiting_for_wifi", resourceCulture);
            }
        }
    }
}
